# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [9]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [58]:
A = np.arange(1, 16).reshape(3,5)

In [60]:
print(f"The number of axes are: {A.ndim}")
print("The shape is:", A.shape, "and the size is:", A.size)
print(f"The datatype of matrix A is {A.dtype}.")

The number of axes are: 2
The shape is: (3, 5) and the size is: 15
The datatype of matrix A is int32.


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [237]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

C = C.astype(int) #snyggar till lite 
print("Matrix B:\n", B)
print("\nMatrix C:\n", C)

print("\nElementwise subtraction using B and C => B-C:\n", B-C) 
print("\nElementwise multiplication using B and C => B*C:\n", B*C) 
print("\nMatrix multiplication using B, C and @ => B@C:\n", B@C) 


Matrix B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix C:
 [[2 2 2]
 [2 2 2]
 [2 2 2]]

Elementwise subtraction using B and C => B-C:
 [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

Elementwise multiplication using B and C => B*C:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Matrix multiplication using B, C and @ => B@C:
 [[12 12 12]
 [30 30 30]
 [48 48 48]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [241]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [382]:
print("Exponentiating B:\n", np.exp(B))
print("\nFinding the smallest value: ", np.min(B))
print("\nSmallest value rowwise: ", np.min(B, axis=1))
print("\nSmallest value columnwise: ", np.min(B, axis=0))


min_index = np.argmin(B)
row_ind, col_ind = np.unravel_index(min_index, B.shape)
print("Index value for minimum value in matrix:", (row_ind, col_ind))


minsta_indexes = np.argmin(B, axis=1)
print("Index value for minimum value rowwise:", minsta_indexes)

             
print("\nCalculating all elements togheter: ", B@B)
print("\nCalculating the mean for each column: ", np.mean(B, axis=0))
print("\nCalculating the median for each column: ", np.median(B, axis = 0))



Exponentiating B:
 [[7.3890561 7.3890561]
 [7.3890561 7.3890561]]

Finding the smallest value:  2

Smallest value rowwise:  [2 2]

Smallest value columnwise:  [2 2]
Index value for minimum value in matrix: (0, 0)
Index value for minimum value rowwise: [0 0]

Calculating all elements togheter:  [[8 8]
 [8 8]]

Calculating the mean for each column:  [2. 2.]

Calculating the median for each column:  [2. 2.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [385]:
print(A)

[[4 4]
 [2 2]]


In [387]:
A[1]

array([2, 2])

**Answer:**

In [390]:
print("When writing fewer indices than axis, the missing index is replaced with colon ':', which returns everything along that specific axis!")

When writing fewer indices than axis, the missing index is replaced with colon ':', which returns everything along that specific axis!


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [393]:
A

array([[4, 4],
       [2, 2]])

In [395]:
for i in A:
    print(i)

[4 4]
[2 2]


In [397]:
for i in np.nditer(A):
    print(i)

4
4
2
2


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [400]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [402]:
print("a is creating an array with elements from 0-29.\nb is creating a copy of a, and shaping it multidimentionally")

a is creating an array with elements from 0-29.
b is creating a copy of a, and shaping it multidimentionally


In [404]:
print("reshaping b with (2, 3, -1) means what there will be two matrices(2), three rows(3).\nAnd the last axis -1 means numpy will calculate the size of the last axis(depending on the amount of elements) so that all elements fit.")

reshaping b with (2, 3, -1) means what there will be two matrices(2), three rows(3).
And the last axis -1 means numpy will calculate the size of the last axis(depending on the amount of elements) so that all elements fit.


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [410]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [413]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [415]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [476]:
def add_mult_matrices(mat_one, mat_two, math_action):
    if isinstance(mat_one, np.ndarray):
        print("Matrix one IS of instance ndarray")
    else:
        print("Matrix one is NOT of instance ndarray")
        return False
    if isinstance(mat_two, np.ndarray):
        print("Matrix two IS of instance ndarray")
    else:
        print("Matrix two is NOT of instance ndarray")
        return False
    if math_action.lower() == "add":
        print("Math action chosen: add.")
        print("Checking if matrices have the same sizes...\n")
        if mat_one.shape == mat_two.shape:
            print("Check complete. Matrices sizes DO match. \n")
            res = mat_one + mat_two
            print("Matrix one added with matrix two is:\n", res)
            return res
        else:
            print("Matrices do NOT have the same size.")
            return False
    elif math_action.lower() == "multiply":
        print("Math action chosen: multiply.")
        print("Checking if matrices sizes conform...\n")
        if mat_one.shape[1] == mat_two.shape[0]:
            print("Check complete. Matrices sizes DO conform. \n")
            result = mat_one @ mat_two
            print("Matrix one multiplied with matrix two is:\n", result)
            return result
        else:
            print("Matrices sizes do NOT conform for multiplication.")
            return False
    else:
        print("Action entered must be 'add' or 'multiply'")
        return False


A = np.array([[4, 4], [2, 2]])
B = np.array([[2, 2], [2, 2]]) 

C = np.array([[1, 2], [3, 4]])
D = np.array([[5, 6], [7, 8]])
OWRONG = np.array([[2], [7]])

X = np.array([[1, 2, 1], [3, 2, 1]])
Y = np.array([[2, 0, 1], [1, 3, 4]])

print("TEST 1:\n")
add_mult_matrices(A, B, 'add')

print("\nTEST 2:\n")
add_mult_matrices(A, B, 'multiply')

print("\nTEST 3:\n")
print(add_mult_matrices(C, D, 'add'))
 
print("\nTEST 4:\n")
print(add_mult_matrices(D, OWRONG, 'add'))

print("\nTEST 5:\n")
print(add_mult_matrices(C, D, 'multiply'))

print("\nTEST 6:\n")
print(add_mult_matrices(X, Y, 'add'))

print("\nTEST 7:\n")
print(add_mult_matrices(X, OWRONG, 'multiply'))


TEST 1:

Matrix one IS of instance ndarray
Matrix two IS of instance ndarray
Math action chosen: add.
Checking if matrices have the same sizes...

Check complete. Matrices sizes DO match. 

Matrix one added with matrix two is:
 [[6 6]
 [4 4]]

TEST 2:

Matrix one IS of instance ndarray
Matrix two IS of instance ndarray
Math action chosen: multiply.
Checking if matrices sizes conform...

Check complete. Matrices sizes DO conform. 

Matrix one multiplied with matrix two is:
 [[16 16]
 [ 8  8]]

TEST 3:

Matrix one IS of instance ndarray
Matrix two IS of instance ndarray
Math action chosen: add.
Checking if matrices have the same sizes...

Check complete. Matrices sizes DO match. 

Matrix one added with matrix two is:
 [[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]

TEST 4:

Matrix one IS of instance ndarray
Matrix two IS of instance ndarray
Math action chosen: add.
Checking if matrices have the same sizes...

Matrices do NOT have the same size.
False

TEST 5:

Matrix one IS of instance ndarray
Ma

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [508]:
a)Eftersom vektorn x har två axlar är den tvådimensionell.
b)5x = (20,15)
c)3x = (12,9)
d)5x + 3x = (20,15)+(12,9) = (32,24)
e)8x = (32,24)
f)4x-x = (16,12)-(4,3) = (12,9)
g)Transponering leder till att man byter dimension mellan vektorer. 
Transponeringen av x= (4,3) leder till att x blir
x=(4
   3), eftersom x var en radvektor och sedan blev en kolumnvektor.
h)x+xT är inte definierat eftersom variablarna har olika dimensioner och för att utföra ekvationer behöver variblerna ha samma dimensioner.
i)||x|| om x=(4,3)
4*4 + 3*3 = 16 + 9 = 25
kvadratroten av 25 = 5
||x|| = 5


SyntaxError: unmatched ')' (92710355.py, line 1)

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [512]:
10.2.1
a)2A = [4 2 -2
        2 -2 2]
b)B - 2A = [0 -4 3
          0 -2 -4]
c)3C - 2E = [1 6
           6 1]
d)2D - 3C = [3 2 
             2 3]

e)DT + 2D = [9 12
             12 9]
f)2CT - 2DT = [-4 -4
               -4 -4]
g)AT - B går inte eftersom de är odefinierat/har olika dimensioner.
h)AC går inte eftersom de är odefinierat/har olika dimensioner.
i)CD = [11 10
        10 11]
j)CB = [8 -10 -3
       10 -8 0]
k)CI = [1 2 
        2 1]
l)ABT = [5 2
        7 4]
10.2.2
AAT när A=[2 3 4
          5 4 1]
 AT=[2 5
     3 4
     4 1]

AAT = [2 3 4
       5 4 1]  [2 5
                3 4
                4 1]

2*2 + 3*3 + 4*4 = 4+9+16 = 29
2*5 + 3*4 + 4*1 = 10+12+4 = 26
5*2 + 4*3 + 1*4 = 10+12+4 = 26
5*5 + 4*4 + 1*1 = 25+16+1 = 42
AAT = [29 26
        26 42]

10.2.3
AB = [1 2] [2 1]
     [2 4] [1 3]   = AB = [4 7]
                          [8 14]
                        
AB = [1 2] [4 3]
     [2 4] [0 2]   AC = [4 7]
                        [8 14]


SyntaxError: unmatched ')' (1294067032.py, line 2)

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [484]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [486]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [490]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [496]:
print("To check if v1 or v2 is a view or a copy you can use the property '.base'.\nIf the variable is a view, '.base' will print the original array.\nIf the variable is the original or a copy, '.base' will print None.\n")
print("If I change the last element in v2 to 123 the last element in v1 will be changed.\nThe reason is v1 and v2 share buffered memory, and v2 is a view of v1. Changing v2 therefore results in changing v1!\n")
print("v2[-1] is the last index of v1, and writing =123 assignes the index value 123.")

To check if v1 or v2 is a view or a copy you can use the property '.base'.
If the variable is a view, '.base' will print the original array.
If the variable is the original or a copy, '.base' will print None.

If I change the last element in v2 to 123 the last element in v1 will be changed.
The reason is v1 and v2 share buffered memory, and v2 is a view of v1. Changing v2 therefore results in changing v1!

v2[-1] is the last index of v1, and writing =123 assignes the index value 123.
